# Generated by Django 4.1.3 on 2022-11-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_item_description_alter_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'Dollars'), ('try', 'Liras')], default='usd', max_length=3),
        ),
    ]
